ORACLE_DSN dbi:Oracle:host=oracle_lh;service_name=FREEPDB1;port=1521
ORACLE_USER lh_user
ORACLE_PWD lh_pwd
SCHEMA LH_USER
TYPE TABLE
OUTPUT schema_postgres.sql
OUTPUT_DIR /data
USER_GRANTS 1
PG_VERSION 16
# SKIP fkeys <- deu problema
FILE_PER_CONSTRAINT 1
FILE_PER_INDEX 1